version: '2'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    command: mongod --smallfiles
    volumes:
      - ./mongo_data:/data/db
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    volumes:
      - ./:/usr/src/app
